### ISSUE TITLE
Todo / Timeline

### ISSUE THREAD

**Issue by amedeedaboville** [amedeedaboville/elixon#1]
- [x] - Port Routes
I've done this by hand, and also written a small script to diff the routes so I know they match exactly. Another todo is productize that script so others can use it.
- [ ] - Port Models over to Phoenix
I've written a tool that converts the rails `db/schema.rb` to Ecto schema defs, but it's very rough. It's good for a start, but it's still missing foreign keys, as well as re-writing constraints in the changeset section. I'd like to productize that too, and that's what I'm working on now.
- [ ] - Set up testing for differences
I'd like to get a setup where I can do API integration tests: send a request to mastodon and one to elixon (with the same db) and compare the outputs
- [ ] - Rewrite the controllers
Work through the controllers here. Tooling can probably be written here too.

- [x] -  Port the JS/CSS/Webpack configs over
Mastodon used webpacker, so I had to modify a few config scripts (hoping to productize that as well) but all is ported over pretty seamlessly. 

- [ ] - Views and Templates
These are hardest IMO (though not that bad). Elixon uses haml for its views, and phoenix supports that through `phoenix_haml`/`calliope`, but those are incomplete. This is also where Rails diverges the most from Phoenix. Rails has a bunch of objects you can call methods on everywhere whereas in Phoenix everything needs to be passed as parameters to templates and views (From what I understand). Additionally, rails uses a lot of indirection with `content_for` which injects content into templates in a different location. So far I haven't figured out a good clean way to mass refactor these.
